config/routes.rb
PersonnelAgency::Application.routes.draw do

  get "pages/home" 
  get "pages/contact"
  get "workers/vacancy_for_workers" 
  #get "users/new"
  
  
  match '/home',   :to => 'pages#home'
  root_path = '/home'
  
  match '/contact', :to => 'pages#contact'
  contact_path = '/contact'
  
  match '/signup', :to => 'users#new'
  signup_path = '/signup'
  
  workers_path = '/workers'
  vacancies_path = '/vacancies'
  
  match '/vacancyworkers', :to => 'workers#vacancy_for_workers'
  vacancy_for_workers_path = '/vacancyworkers'

  root :to => 'pages#home'

  resources :statuses
  resources :skillgroups
  resources :skills
  resources :contactinformations
  resources :workers
  resources :vacancies 
  resources :users

end

app/models/skillgroup.rb
class Skillgroup < ActiveRecord::Base
  attr_accessible :parent_id, :parent_type, :skill

end

app/controllers/skillgroups_controller.rb
class SkillgroupsController < ApplicationController
  # GET /skillgroups
  # GET /skillgroups.json
  def index
    @skillgroups = Skillgroup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @skillgroups }
    end
  end

  # GET /skillgroups/1
  # GET /skillgroups/1.json
  def show
    @skillgroup = Skillgroup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @skillgroup }
    end
  end

  # GET /skillgroups/new
  # GET /skillgroups/new.json
  def new
    @skillgroup = Skillgroup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @skillgroup }
    end
  end

  # GET /skillgroups/1/edit
  def edit
    @skillgroup = Skillgroup.find(params[:id])
  end

  # POST /skillgroups
  # POST /skillgroups.json
  def create
    @skillgroup = Skillgroup.new(params[:skillgroup])

    respond_to do |format|
      if @skillgroup.save
        format.html { redirect_to @skillgroup, notice: 'Skillgroup was successfully created.' }
        format.json { render json: @skillgroup, status: :created, location: @skillgroup }
      else
        format.html { render action: "new" }
        format.json { render json: @skillgroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /skillgroups/1
  # PUT /skillgroups/1.json
  def update
    @skillgroup = Skillgroup.find(params[:id])

    respond_to do |format|
      if @skillgroup.update_attributes(params[:skillgroup])
        format.html { redirect_to @skillgroup, notice: 'Skillgroup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @skillgroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skillgroups/1
  # DELETE /skillgroups/1.json
  def destroy
    @skillgroup = Skillgroup.find(params[:id])
    @skillgroup.destroy

    respond_to do |format|
      format.html { redirect_to skillgroups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/skillgroups_helper.rb
module SkillgroupsHelper
end

app/views/skillgroups/_form.html.erb
<%= form_for(@skillgroup) do |f| %>
  <% if @skillgroup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@skillgroup.errors.count, "error") %> prohibited this skillgroup from being saved:</h2>

      <ul>
      <% @skillgroup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :seniorid %><br />
    <%= f.number_field :seniorid %>
  </div>
  <div class="field">
    <%= f.label :skill %><br />
    <%= f.number_field :skill %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/skillgroups/edit.html.erb
<h1>Editing skillgroup</h1>

<%= render 'form' %>

<%= link_to 'Show', @skillgroup %> |
<%= link_to 'Back', skillgroups_path %>

app/views/skillgroups/index.html.erb
<h1>Listing skillgroups</h1>

<table>
  <tr>
    <th>Seniorid</th>
    <th>Skill</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @skillgroups.each do |skillgroup| %>
  <tr>
    <td><%= skillgroup.seniorid %></td>
    <td><%= skillgroup.skill %></td>
    <td><%= link_to 'Show', skillgroup %></td>
    <td><%= link_to 'Edit', edit_skillgroup_path(skillgroup) %></td>
    <td><%= link_to 'Destroy', skillgroup, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Skillgroup', new_skillgroup_path %>

app/views/skillgroups/new.html.erb
<h1>New skillgroup</h1>

<%= render 'form' %>

<%= link_to 'Back', skillgroups_path %>

app/views/skillgroups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Seniorid:</b>
  <%= @skillgroup.seniorid %>
</p>

<p>
  <b>Skill:</b>
  <%= @skillgroup.skill %>
</p>


<%= link_to 'Edit', edit_skillgroup_path(@skillgroup) %> |
<%= link_to 'Back', skillgroups_path %>