config/routes.rb
PersonnelAgency::Application.routes.draw do

  get "pages/home" 
  get "pages/contact"
  get "workers/vacancy_for_workers" 
  #get "users/new"
  
  
  match '/home',   :to => 'pages#home'
  root_path = '/home'
  
  match '/contact', :to => 'pages#contact'
  contact_path = '/contact'
  
  match '/signup', :to => 'users#new'
  signup_path = '/signup'
  
  workers_path = '/workers'
  vacancies_path = '/vacancies'
  
  match '/vacancyworkers', :to => 'workers#vacancy_for_workers'
  vacancy_for_workers_path = '/vacancyworkers'

  root :to => 'pages#home'

  resources :statuses
  resources :skillgroups
  resources :skills
  resources :contactinformations
  resources :workers
  resources :vacancies 
  resources :users

end

app/models/contactinformation.rb
class Contactinformation < ActiveRecord::Base
  #attr_accessible :email, :telephone
  belongs_to :contactinfo, :polymorphic => true
  accepts_nested_attributes_for :contactinfo
end

app/controllers/contactinformations_controller.rb
class ContactinformationsController < ApplicationController

  def index
    @contactinformations = Contactinformation.all

    respond_to do |format|
      format.html 
      format.json { render json: @contactinformations }
    end
  end

  def show
    @contactinformation = Contactinformation.find(params[:id])

    respond_to do |format|
      format.html 
      format.json { render json: @contactinformation }
    end
  end


  def new
    @contactinformation = Contactinformation.new

    respond_to do |format|
      format.html 
      format.json { render json: @contactinformation }
    end
  end

  def edit
    @contactinformation = Contactinformation.find(params[:id])
  end

  def create
    @contactinformation = Contactinformation.new(params[:contactinformation])    
    #@vacancy = Vacancy.find(params[:contactinformation_id])      
    #@contactinformation = @vacancy.contactinformations.create(params[:contactinfo])  
    

    #@contactinformation = @vacancy.contactinformations.create(params[:contactinformation])
    #redirect_tog post_path(@vacancy)

    respond_to do |format|
      if @contactinformation.save
        format.html { redirect_to @contactinformation, notice: 'Contactinformation was successfully created.' }
        format.json { render json: @contactinformation, status: :created, location: @contactinformation }
      else
        format.html { render action: "new" }
        format.json { render json: @contactinformation.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @contactinformation = Contactinformation.find(params[:id])

    respond_to do |format|
      if @contactinformation.update_attributes(params[:contactinformation])
        format.html { redirect_to @contactinformation, notice: 'Contactinformation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contactinformation.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @contactinformation = Contactinformation.find(params[:id])
    @contactinformation.destroy

    respond_to do |format|
      format.html { redirect_to contactinformations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/contactinformations_helper.rb
module ContactinformationsHelper
end

app/views/contactinformations/_form.html.erb
<%= form_for(contactinformation) do |contactinfo_form| %>
  <% if @contactinformation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contactinformation.errors.count, "error") %> prohibited this vacancy from being saved:</h2>
      <ul>
      <% @contactinformation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= contactinfo_form.label :"Телефон" %><br />
    <%= contactinfo_form.text_field :telephone %>
  </div>
  <div class="field">
    <%= contactinfo_form.label :"E-mail" %><br />
    <%= contactinfo_form.email_field :email %>
  </div>
<% end %>

app/views/contactinformations/edit.html.erb
<h1>Editing contactinformation</h1>

<%= render 'form' %>

<%= link_to 'Show', @contactinformation %> |
<%= link_to 'Back', contactinformations_path %>

app/views/contactinformations/index.html.erb
<h1>Listing contactinformations</h1>

<table>
  <tr>
    <th>Telephone</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contactinformations.each do |contactinformation| %>
  <tr>
    <td><%= contactinformation.telephone %></td>
    <td><%= contactinformation.email %></td>
    <td><%= link_to 'Show', contactinformation %></td>
    <td><%= link_to 'Edit', edit_contactinformation_path(contactinformation) %></td>
    <td><%= link_to 'Destroy', contactinformation, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contactinformation', new_contactinformation_path %>

app/views/contactinformations/new.html.erb
<h1>New contactinformation</h1>

<%= render 'form' %>

<%= link_to 'Back', contactinformations_path %>

app/views/contactinformations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Telephone:</b>
  <%= @contactinformation.telephone %>
</p>

<p>
  <b>Email:</b>
  <%= @contactinformation.email %>
</p>


<%= link_to 'Edit', edit_contactinformation_path(@contactinformation) %> |
<%= link_to 'Back', contactinformations_path %>